// Added by the desuqcafe fork. Upstream has no such directory, so this file
// can never conflict on a merge.
//
// Three lists of 256 words. Combined with a rank of 0-255 they name one of
// 2^32 possible values -- see deviceHandshakeDirective.js for how a pair of
// device IDs is reduced to one.
//
// THE LISTS ARE DATA, NOT PROSE. Two rules hold for every list, and both are
// enforced by custom/scripts/check-handshake-words.ps1, which the Windows
// build runs:
//
//   1. No two words in a list share their first three letters.
//   2. No two words in a list are closer than a Levenshtein distance of 3.
//
// Both exist because these words get read aloud down a phone line by someone
// who is not concentrating. "SLASH" and "CLASH" differing in one letter would
// make a mismatch sound like a match, which is the one failure this whole
// mechanism has to avoid. Adding a word by hand without re-running the
// checker is how that protection gets lost.
//
// Order is significant: a word's INDEX is its meaning. Re-ordering the lists,
// or inserting into the middle of one, changes the phrase every already-paired
// device computes and silently invalidates every verification anyone has done.
// Append only, and only up to 256.

angular.module('syncthing.core')
    .constant('desuqHandshakeWords', {
        // index 0-255
        aspect: [
            'CRIMSON', 'AZURE', 'OBSIDIAN', 'GOLDEN',
            'SILVER', 'EMBER', 'FROZEN', 'RADIANT',
            'VERDANT', 'COBALT', 'SCARLET', 'IVORY',
            'ONYX', 'JADE', 'VIOLET', 'INDIGO',
            'SAPPHIRE', 'EMERALD', 'RUBY', 'TOPAZ',
            'PEARL', 'BRONZE', 'COPPER', 'PLATINUM',
            'TITANIUM', 'IRON', 'STEEL', 'CHROME',
            'ASHEN', 'DUSKY', 'PALLID', 'MAGENTA',
            'CERULEAN', 'TURQUOISE', 'VIRIDIAN', 'OCHRE',
            'SIENNA', 'RUSSET', 'MAROON', 'BURGUNDY',
            'PLUM', 'LILAC', 'LAVENDER', 'MAUVE',
            'SALMON', 'APRICOT', 'SAFFRON', 'MUSTARD',
            'OLIVE', 'MOSS', 'FERN', 'MINT',
            'CYAN', 'NAVY', 'MIDNIGHT', 'TWILIGHT',
            'SOLAR', 'LUNAR', 'ASTRAL', 'COSMIC',
            'ABYSSAL', 'INFERNAL', 'CELESTIAL', 'DIVINE',
            'SACRED', 'CURSED', 'BLESSED', 'ANCIENT',
            'ETERNAL', 'IMMORTAL', 'PRIMAL', 'SAVAGE',
            'FIERCE', 'BRUTAL', 'RUTHLESS', 'MERCILESS',
            'HIDDEN', 'SPECTRAL', 'GHOSTLY', 'HOLLOW',
            'VACANT', 'GLACIAL', 'ARCTIC', 'BOREAL',
            'BLAZING', 'SEARING', 'SCORCHING', 'VOLCANIC',
            'THUNDEROUS', 'STORMY', 'GENTLE', 'TENDER',
            'QUIET', 'SORROWFUL', 'JOYFUL', 'SERENE',
            'TRANQUIL', 'RESTLESS', 'WITHERED', 'FRAGILE',
            'BRITTLE', 'JAGGED', 'SMOOTH', 'POLISHED',
            'GLEAMING', 'GLISTENING', 'SPARKLING', 'SHIMMERING',
            'GLOWING', 'LUMINOUS', 'DAZZLING', 'BLINDING',
            'CLOUDY', 'FOGGY', 'VEILED', 'SHROUDED',
            'MASKED', 'CROWNED', 'JEWELED', 'WINGED',
            'HORNED', 'CLAWED', 'ARMORED', 'BARBED',
            'SPIKED', 'SHATTERED', 'CRACKED', 'SPLINTERED',
            'RUINED', 'FALLEN', 'RISEN', 'AWAKENED',
            'SLUMBERING', 'WAKING', 'WANDERING', 'ROAMING',
            'DRIFTING', 'SURGING', 'SWELLING', 'EBBING',
            'RIPPLING', 'CASCADING', 'HOWLING', 'WHISPERING',
            'MURMURING', 'CHANTING', 'KEENING', 'LAUGHING',
            'SMILING', 'WOUNDED', 'BRANDED', 'CHOSEN',
            'FORSAKEN', 'REMEMBERED', 'HONORED', 'EXALTED',
            'HUMBLE', 'NOBLE', 'ROYAL', 'IMPERIAL',
            'SOVEREIGN', 'GALLANT', 'STALWART', 'UNYIELDING',
            'RELENTLESS', 'TIRELESS', 'BOUNDLESS', 'LIMITLESS',
            'ENDLESS', 'AGELESS', 'DEATHLESS', 'FEARLESS',
            'MATCHLESS', 'VOICELESS', 'WEIGHTLESS', 'BODILESS',
            'WRATHFUL', 'VENGEFUL', 'MOURNFUL', 'DOLEFUL',
            'WISTFUL', 'FAITHFUL', 'DEVOTED', 'SWORN',
            'FETTERED', 'FREED', 'UNBOUND', 'UNCHAINED',
            'LIBERATED', 'BANISHED', 'OUTCAST', 'NOMADIC',
            'PILGRIM', 'WATCHING', 'GUARDING', 'SHELTERING',
            'HARBORING', 'GRASPING', 'CLUTCHING', 'LONGING',
            'HUNGERING', 'THIRSTING', 'BLOOMING', 'FLOWERING',
            'BUDDING', 'SPROUTING', 'FRUITING', 'KINDLED',
            'KNOTTED', 'LACQUERED', 'LANGUID', 'LITHE',
            'LURID', 'LUSH', 'NOCTURNAL', 'NUMBING',
            'OPULENT', 'ORNATE', 'OVERGROWN', 'PROUD',
            'PRUDENT', 'PUNGENT', 'UNDAUNTED', 'UNSEEN',
            'UPRIGHT', 'VAGUE', 'VELVET', 'VIGILANT',
            'VIVID', 'YAWNING', 'ZEALOUS', 'ZIGZAG',
            'XENIAL', 'DAPPLED', 'DEFIANT', 'DELICATE',
            'DILIGENT', 'DORMANT', 'DOWNCAST', 'DRENCHED',
            'DROWSY', 'EARNEST', 'EBONY', 'EFFULGENT',
            'ELDRITCH', 'ELOQUENT', 'GAUNT', 'GERMINAL',
            'GIDDY', 'GNARLED', 'GRIM', 'GRUFF',
            'HALLOWED', 'HAPLESS', 'HAUGHTY', 'HEADLONG'
        ],
        // index 0-255
        omen: [
            'MOONLIGHT', 'THUNDER', 'BLOSSOM', 'TEMPEST',
            'ECLIPSE', 'STARFALL', 'SUNRISE', 'DAYBREAK',
            'NIGHTFALL', 'DAWNLIGHT', 'TWILIGHT', 'MIDNIGHT',
            'AURORA', 'COMET', 'METEOR', 'NEBULA',
            'GALAXY', 'COSMOS', 'ZENITH', 'NADIR',
            'HORIZON', 'SKYLINE', 'CLOUDBANK', 'RAINFALL',
            'SNOWFALL', 'HAILSTORM', 'WINDSTORM', 'FIRESTORM',
            'LIGHTNING', 'WHIRLWIND', 'CYCLONE', 'TORNADO',
            'HURRICANE', 'MONSOON', 'TYPHOON', 'BLIZZARD',
            'AVALANCHE', 'LANDSLIDE', 'EARTHQUAKE', 'VOLCANO',
            'GEYSER', 'WATERFALL', 'MAELSTROM', 'RIPTIDE',
            'UNDERTOW', 'TIDEWATER', 'SEAFOAM', 'SALTSPRAY',
            'OCEANWAVE', 'RIVERBEND', 'CREEKBED', 'LAKESHORE',
            'PONDLILY', 'MARSHLAND', 'WETLAND', 'HEATHER',
            'BRAMBLE', 'THICKET', 'COPPICE', 'WOODLAND',
            'FORESTRY', 'GROVETREE', 'ORCHARD', 'VINEYARD',
            'MEADOW', 'PASTURE', 'PRAIRIE', 'SAVANNA',
            'STEPPE', 'TUNDRA', 'DESERT', 'OASIS',
            'CANYON', 'GORGE', 'RAVINE', 'VALLEY',
            'HIGHLAND', 'LOWLAND', 'MOUNTAIN', 'FOOTHILL',
            'RIDGELINE', 'SUMMIT', 'PLATEAU', 'MESA',
            'BUTTE', 'CLIFFSIDE', 'SHORELINE', 'COASTLINE',
            'PENINSULA', 'ARCHIPELAGO', 'GLACIER', 'ICEBERG',
            'FROSTBITE', 'ICICLE', 'HOARFROST', 'PERMAFROST',
            'DEWDROP', 'MISTVEIL', 'FOGBANK', 'SMOKESCREEN',
            'CINDERASH', 'EMBERGLOW', 'FLAMEHEART', 'BONFIRE',
            'WILDFIRE', 'INFERNO', 'BRIMSTONE', 'MAGMA',
            'LAVAFLOW', 'CRYSTAL', 'GEMSTONE', 'DIAMOND',
            'QUARTZ', 'GRANITE', 'LIMESTONE', 'SANDSTONE',
            'BEDROCK', 'PEBBLE', 'BOULDER', 'OBELISK',
            'PILLAR', 'COLUMN', 'GATEWAY', 'DOORWAY',
            'THRESHOLD', 'CORRIDOR', 'CHAMBER', 'SHRINE',
            'CATHEDRAL', 'CITADEL', 'BASTION', 'RAMPART',
            'BATTLEMENT', 'BEACON', 'SIGNALFIRE', 'LAMPLIGHT',
            'GLIMMER', 'RADIANCE', 'SPLENDOR', 'GLORY',
            'MAJESTY', 'ELEGANCE', 'WONDER', 'MIRACLE',
            'BLESSING', 'PROMISE', 'COVENANT', 'OATHBOUND',
            'VOWKEEPER', 'PLEDGE', 'TESTAMENT', 'PORTENT',
            'AUGURY', 'DIVINATION', 'VISION', 'REVERIE',
            'SLUMBER', 'REPOSE', 'STILLNESS', 'SILENCE',
            'MURMUR', 'ECHO', 'HARMONY', 'MELODY',
            'SONATA', 'RHAPSODY', 'SYMPHONY', 'CONCERTO',
            'BALLAD', 'ANTHEM', 'HYMN', 'CAROL',
            'LULLABY', 'SERENADE', 'OVERTURE', 'PRELUDE',
            'INTERLUDE', 'FINALE', 'CADENCE', 'REFRAIN',
            'CHORUS', 'VERSE', 'POETRY', 'LYRIC',
            'LEGEND', 'MYTHOS', 'EPIC', 'CHRONICLE',
            'ANNAL', 'ARTIFACT', 'HEIRLOOM', 'TREASURE',
            'TALISMAN', 'AMULET', 'RUNESTONE', 'GLYPH',
            'INSIGNIA', 'BANNER', 'REGALIA', 'CIRCLET',
            'TIARA', 'SCEPTER', 'ORB', 'GOBLET',
            'PLUMAGE', 'QUILL', 'FLETCHING', 'ARROWSHAFT',
            'BOWSTRING', 'PETAL', 'CHERRYBLOOM', 'LOTUSPOND',
            'CAMELLIA', 'WISTERIA', 'PEONY', 'GARDENIA',
            'JASMINE', 'HIBISCUS', 'IRIS', 'LILY',
            'TULIP', 'DAFFODIL', 'DAISY', 'POPPY',
            'KETTLEDRUM', 'KINDLING', 'KNAPSACK', 'KNOTWORK',
            'JUNIPER', 'JUBILEE', 'JIGSAW', 'ZODIAC',
            'ZEPHYRWIND', 'YARDARM', 'YEWTREE', 'YULETIDE',
            'XYLEM', 'WAYPOINT', 'WELLSPRING', 'WHETSTONE',
            'UPLANDS', 'URCHIN', 'VESTIBULE', 'VIADUCT',
            'VIGILWATCH', 'VOYAGE', 'NUTMEG', 'NECTARINE',
            'NOONTIDE', 'OFFERING', 'OUTPOST', 'KESTREL',
            'ELDERWOOD', 'ENCLAVE', 'ESTUARY', 'EVERGLADE'
        ],
        // index 0-255
        strike: [
            'SLASH', 'FANG', 'REQUIEM', 'HOWL',
            'BARRAGE', 'STRIKE', 'THRUST', 'PARRY',
            'RIPOSTE', 'LUNGE', 'CLEAVE', 'SUNDER',
            'REND', 'SHRED', 'PIERCE', 'IMPALE',
            'SKEWER', 'SPEAR', 'JAVELIN', 'HARPOON',
            'CRESCENT', 'ARC', 'SWEEP', 'SPIRAL',
            'VORTEX', 'CYCLONESPIN', 'WHIRL', 'PIVOT',
            'FEINT', 'DODGE', 'BLINK', 'FLICKER',
            'PHASE', 'RIFT', 'FRACTURE', 'SHATTER',
            'SPLINTER', 'CRUSH', 'PULVERIZE', 'HAMMER',
            'MAUL', 'BLUDGEON', 'POUND', 'SMITE',
            'JUDGMENT', 'VERDICT', 'SENTENCE', 'RECKONING',
            'RETRIBUTION', 'VENGEANCE', 'GRUDGE', 'MALICE',
            'WRATH', 'FURY', 'RAGE', 'TANTRUM',
            'OUTBURST', 'ERUPTION', 'DETONATION', 'EXPLOSION',
            'COLLAPSE', 'CASCADE', 'DELUGE', 'TORRENT',
            'FLOOD', 'TIDALWAVE', 'UNDERCUT', 'BACKHAND',
            'PALMSTRIKE', 'FISTFALL', 'KNUCKLE', 'ELBOW',
            'KNEEDROP', 'HEELKICK', 'ROUNDHOUSE', 'AXEKICK',
            'FLYINGKNEE', 'TACKLE', 'GRAPPLE', 'CHOKEHOLD',
            'ARMBAR', 'SUPLEX', 'PILEDRIVER', 'BODYSLAM',
            'TOSS', 'LAUNCH', 'CATAPULT', 'TREBUCHET',
            'BALLISTA', 'CANNONADE', 'FUSILLADE', 'VOLLEY',
            'SALVO', 'BOMBARDMENT', 'SIEGE', 'BLOCKADE',
            'AMBUSH', 'SORTIE', 'SKIRMISH', 'DUEL',
            'GAUNTLET', 'TOURNAMENT', 'TRIAL', 'ORDEAL',
            'GAMBIT', 'PLOY', 'MANEUVER', 'FORMATION',
            'VANGUARD', 'REARGUARD', 'PINCER', 'ENCIRCLEMENT',
            'ENTRAPMENT', 'SNARE', 'DEADFALL', 'LANDMINE',
            'BOOBYTRAP', 'DECOY', 'ILLUSION', 'APPARITION',
            'BANSHEE', 'POLTERGEIST', 'REVENANT', 'LICH',
            'ZOMBIE', 'VAMPIRE', 'WEREWOLF', 'CHIMERA',
            'BASILISK', 'COCKATRICE', 'HYDRA', 'KRAKEN',
            'LEVIATHAN', 'BEHEMOTH', 'TITAN', 'GOLEM',
            'GARGOYLE', 'SPHINX', 'GRIFFIN', 'PEGASUS',
            'UNICORN', 'DRAGONFANG', 'SERPENTCOIL', 'VIPERBITE',
            'COBRASTRIKE', 'HORNETSWARM', 'LOCUSTPLAGUE', 'WASPNEST',
            'BEESTING', 'TALONRAKE', 'CLAWSWIPE', 'BEAKPECK',
            'WINGBUFFET', 'TAILWHIP', 'HOOFSTOMP', 'TUSKCHARGE',
            'PELTBRISTLE', 'BLADEDANCE', 'SWORDSONG', 'SABERWALTZ',
            'RAPIERPOEM', 'KATANADRAW', 'IAIDOCUT', 'KENDOSTANCE',
            'BUSHIDOOATH', 'RONINPATH', 'SAMURAIVOW', 'NINJUTSU',
            'SHURIKEN', 'KUNAI', 'CALTROP', 'SMOKEBOMB',
            'FLASHBANG', 'GRENADE', 'MORTAR', 'ARTILLERY',
            'LASERBEAM', 'PLASMABOLT', 'IONBLAST', 'PHOTONRAY',
            'ENERGYWAVE', 'SHOCKWAVE', 'SONICBOOM', 'THUNDERCLAP',
            'LIGHTNINGROD', 'STORMCALL', 'RAINDANCE', 'GALEFORCE',
            'ZEPHYRTOUCH', 'BREEZEWALK', 'TWISTERPULL', 'FIREBALL',
            'INFERNOBLAST', 'EMBERSTORM', 'CINDERRAIN', 'ASHCLOUD',
            'SCORCHMARK', 'BURNSCAR', 'HEATHAZE', 'ICELANCE',
            'GLACIERSPIKE', 'SNOWSQUALL', 'HAILBARRAGE', 'SLEETSTORM',
            'RIMEFROST', 'EARTHSHATTER', 'ROCKSLIDE', 'BOULDERTOSS',
            'QUAKESTEP', 'CHASMOPEN', 'CAVERNMAW', 'ABYSSDIVE',
            'VOIDSTEP', 'DARKPACT', 'NIGHTVEIL', 'GLOOMSHROUD',
            'DUSKFALL', 'ECLIPSEBIND', 'UMBRAGRASP', 'PENUMBRASTEP',
            'NOCTURNE', 'DAWNBREAK', 'SOLARFLARE', 'RADIANTBEAM',
            'HALOCROWN', 'AUREOLE', 'NIMBUSRING', 'SANCTUSCALL',
            'BENEDICTION', 'ABSOLUTION', 'REDEMPTION', 'ATONEMENT',
            'CONFESSION', 'LAMENTATION', 'ELEGY', 'YAWP',
            'YOKEBREAK', 'ZEALSTRIKE', 'ZENITHCUT', 'XIPHOID',
            'WITHERTOUCH', 'UNMAKING', 'UNRAVELING', 'UPHEAVAL',
            'UTTERANCE', 'VAULTLEAP', 'VEILREND', 'VOWBREAK',
            'NAILBITE', 'NECKSNAP', 'NOOSEDROP', 'NOVABURST',
            'OATHSTRIKE', 'OBLIVION', 'OVERRUN', 'QUELLING'
        ]
    });
